const steps=['infra','deploy','security','evidence'];
const stepNames={infra:'Infraestructura',deploy:'Despliegue',security:'Seguridad',evidence:'Evidencias'};
const systems={
 'SIS-MAT-01':'Sistema de Matrícula','SIS-DOC-02':'Documenta','SIS-VEN-03':'Registro de Ventas','SIS-BIB-04':'Biblioteca Virtual','SIS-RRH-05':'Control de Personal','SIS-MSA-06':'Mesa de Servicios TI','SIS-PAG-07':'Portal de Pagos','SIS-ADM-08':'Gestión Administrativa','SIS-INV-09':'Sistema de Investigación','SIS-COM-10':'Comedor Universitario'
};
const defaultStates={'SIS-MAT-01':'Validado','SIS-DOC-02':'Observado','SIS-VEN-03':'Borrador','SIS-BIB-04':'Corregido','SIS-RRH-05':'Enviado','SIS-MSA-06':'Nuevo','SIS-PAG-07':'Observado','SIS-ADM-08':'Observado','SIS-INV-09':'Observado','SIS-COM-10':'Observado'};
const sampleDrafts={'SIS-VEN-03':{estado:'Borrador',ultimoPaso:0,data:{plataforma:'Servidor físico',tipoServidor:'Físico',sistemaOperativo:'Windows Server',versionSO:'2019',ipPrivada:'192.168.10.30',proxmox:'No',backup:'Sí',frecuenciaBackup:'Semanal',observacionesInfra:'Registro técnico pendiente de completar.',evidences:[]}}};
function stateOf(code){const saved=localStorage.getItem(`diagti-estado-${code}`);if(saved)return saved;try{const r=JSON.parse(localStorage.getItem(key(code))||'null');if(r?.estado)return r.estado}catch{}return defaultStates[code]||'Nuevo'}
function populateSystems(){systemSelect.innerHTML='<option value="">Seleccione un sistema</option>';Object.entries(systems).forEach(([code,name])=>{const st=stateOf(code);if(st==='Nuevo'||st==='Borrador')systemSelect.insertAdjacentHTML('beforeend',`<option value="${code}">${code} — ${name} (${st})</option>`)});}
function addHistory(code,action,detail,state,section,after){let h=[];try{h=JSON.parse(localStorage.getItem('diagti-historial')||'[]')}catch{}h.unshift({id:`evt-${Date.now()}-${Math.random().toString(16).slice(2)}`,date:new Date().toISOString(),code,name:systems[code],action,detail,user:'Carlos Rojas',state,section,after});localStorage.setItem('diagti-historial',JSON.stringify(h.slice(0,200)))}
let currentStep=0,currentSystem='',pendingSystem='',dirty=false,evidences=[],editingEvidence=-1;
const form=document.getElementById('formTecnico'), systemSelect=document.getElementById('sistema'), message=document.getElementById('mensaje');
const btnAnterior=document.getElementById('btnAnterior'),btnContinuar=document.getElementById('btnContinuar'),btnDraft=document.getElementById('btnGuardarBorrador'),btnSend=document.getElementById('btnEnviar');
function key(code){return `diagti-registro-${code}`}
function showModal(id){document.getElementById(id).classList.add('show')}
function hideModal(id){document.getElementById(id).classList.remove('show')}
function showStep(i){currentStep=Math.max(0,Math.min(steps.length-1,i));document.querySelectorAll('.step-panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.step').forEach(x=>x.classList.remove('active'));document.getElementById(steps[currentStep]).classList.add('active');document.querySelector(`.step[data-step="${steps[currentStep]}"]`).classList.add('active');btnAnterior.classList.toggle('hidden',currentStep===0);btnContinuar.classList.toggle('hidden',currentStep===steps.length-1);btnDraft.classList.toggle('hidden',currentStep!==steps.length-1);btnSend.classList.toggle('hidden',currentStep!==steps.length-1);message.textContent=''}
function formData(){const d={};[...form.elements].forEach(el=>{if(el.name&&el.type!=='file'&&el.tagName!=='BUTTON')d[el.name]=el.value});return d}
function fillForm(d={}){form.reset();[...form.elements].forEach(el=>{if(el.name&&el.type!=='file'&&d[el.name]!==undefined)el.value=d[el.name]});evidences=Array.isArray(d.evidences)?d.evidences:[];renderEvidences()}
function currentRecord(){if(!currentSystem)return null;try{return JSON.parse(localStorage.getItem(key(currentSystem))||'null')}catch{return null}}
function updateStatus(){const r=currentRecord();const savedState=currentSystem?localStorage.getItem(`diagti-estado-${currentSystem}`):'';const badge=document.getElementById('estadoRegistro');const isDraft=(r&&r.estado==='Borrador')||savedState==='Borrador'||stateOf(currentSystem)==='Borrador';badge.textContent=isDraft?'Borrador':'Nuevo';badge.className=`status-badge ${isDraft?'draft':'new'}`;document.getElementById('selectorAyuda').textContent=isDraft?'Se cargaron automáticamente los datos guardados como borrador.':'Nuevo registro técnico. Complete los cuatro pasos.'}
function loadSystem(code){currentSystem=code;let r=currentRecord();if(!r&&sampleDrafts[code])r=sampleDrafts[code];fillForm(r?.data||{});showStep(Number.isInteger(r?.ultimoPaso)?r.ultimoPaso:0);dirty=false;updateStatus();markCompleted()}
function saveDraft(show=true){if(!currentSystem){message.className='message error';message.textContent='Seleccione un sistema.';return}const payload={estado:'Borrador',data:{...formData(),evidences},ultimoPaso:currentStep,updatedAt:new Date().toLocaleString('es-PE')};localStorage.setItem(key(currentSystem),JSON.stringify(payload));localStorage.setItem(`diagti-estado-${currentSystem}`,'Borrador');addHistory(currentSystem,'Borrador','Se guardó el avance del registro técnico.','Borrador','Registro técnico','Borrador');dirty=false;updateStatus();hideModal('modalIncompleto');if(show){message.className='message success';message.textContent='Borrador guardado. Puede seguir editándolo cuando desee.'}}
function requiredFields(step){return [...document.querySelectorAll(`#${step} [required]`)]}
function validateStep(step,mark=true){let ok=true;requiredFields(step).forEach(el=>{const good=el.checkValidity()&&String(el.value).trim()!=='';if(mark)el.classList.toggle('invalid',!good);if(!good)ok=false});if(step==='evidence'&&evidences.length===0)ok=false;return ok}
function pending(){const p=[];if(!currentSystem)p.push('Sistema');steps.forEach(s=>{if(!validateStep(s,false))p.push(stepNames[s])});return p}
function markCompleted(){steps.forEach(s=>document.querySelector(`.step[data-step="${s}"]`).classList.toggle('completed',validateStep(s,false)))}
function requestSystemChange(next){if(!currentSystem||next===currentSystem){if(next)loadSystem(next);return}pendingSystem=next;const saved=!dirty;document.getElementById('textoCambio').textContent=saved?'Este registro ya está guardado. ¿Desea abrir otro sistema?':'Tiene cambios sin guardar. Si cambia de sistema, perderá la información no guardada.';showModal('modalCambio')}
systemSelect.addEventListener('change',e=>{const next=e.target.value;if(!next){e.target.value=currentSystem;return}e.target.value=currentSystem;requestSystemChange(next)});
document.getElementById('btnPermanecer').onclick=()=>{pendingSystem='';systemSelect.value=currentSystem;hideModal('modalCambio')};
document.getElementById('btnCambiar').onclick=()=>{hideModal('modalCambio');systemSelect.value=pendingSystem;loadSystem(pendingSystem);pendingSystem=''};
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>showStep(steps.indexOf(b.dataset.step)));
btnContinuar.onclick=()=>{if(!currentSystem){message.className='message error';message.textContent='Seleccione un sistema antes de continuar.';return}if(!validateStep(steps[currentStep],true)){message.className='message error';message.textContent='Complete los campos obligatorios antes de continuar.';return}markCompleted();showStep(currentStep+1)};
btnAnterior.onclick=()=>showStep(currentStep-1);
document.getElementById('btnCancelar').onclick=()=>{if(confirm('¿Desea descartar los cambios no guardados?')){const r=currentRecord();fillForm(r?.data||{});dirty=false;showStep(Number.isInteger(r?.ultimoPaso)?r.ultimoPaso:0)}};
form.addEventListener('input',e=>{dirty=true;e.target.classList.remove('invalid')});form.addEventListener('change',e=>{dirty=true;e.target.classList.remove('invalid')});
function evidenceInput(){return {tipo:document.getElementById('evTipo'),nombre:document.getElementById('evNombre'),archivo:document.getElementById('evArchivo'),url:document.getElementById('evUrl'),descripcion:document.getElementById('evDescripcion')}}
function clearEvidence(){const x=evidenceInput();x.tipo.value='';x.nombre.value='';x.archivo.value='';x.url.value='';x.descripcion.value='';editingEvidence=-1;document.getElementById('btnAgregarEvidencia').textContent='Agregar evidencia'}
function renderEvidences(){const body=document.getElementById('tablaEvidencias');document.getElementById('contadorEvidencias').textContent=evidences.length;if(!evidences.length){body.innerHTML='<tr class="empty-row"><td colspan="5">Todavía no se agregaron evidencias.</td></tr>';return}body.innerHTML=evidences.map((e,i)=>`<tr><td>${e.tipo}</td><td>${e.nombre}</td><td>${e.archivo||e.url}</td><td>${e.descripcion||'—'}</td><td><button type="button" class="table-btn edit-ev" data-i="${i}">Editar</button><button type="button" class="table-btn delete-ev" data-i="${i}">Eliminar</button></td></tr>`).join('');body.querySelectorAll('.edit-ev').forEach(b=>b.onclick=()=>editEvidence(+b.dataset.i));body.querySelectorAll('.delete-ev').forEach(b=>b.onclick=()=>{evidences.splice(+b.dataset.i,1);dirty=true;renderEvidences();markCompleted()})}
function editEvidence(i){const e=evidences[i],x=evidenceInput();x.tipo.value=e.tipo;x.nombre.value=e.nombre;x.url.value=e.url||'';x.descripcion.value=e.descripcion||'';x.archivo.value='';editingEvidence=i;document.getElementById('btnAgregarEvidencia').textContent='Actualizar evidencia';window.scrollTo({top:document.getElementById('evidence').offsetTop-20,behavior:'smooth'})}
document.getElementById('btnAgregarEvidencia').onclick=()=>{const x=evidenceInput(),file=x.archivo.files[0]?.name||'',err=document.getElementById('errorEvidencia');if(!x.tipo.value||!x.nombre.value.trim()||(!file&&!x.url.value.trim())){err.textContent='Complete tipo, nombre y agregue un archivo o una URL.';return}const old=editingEvidence>=0?evidences[editingEvidence]:{};const ev={tipo:x.tipo.value,nombre:x.nombre.value.trim(),archivo:file||old.archivo||'',url:x.url.value.trim(),descripcion:x.descripcion.value.trim()};if(editingEvidence>=0)evidences[editingEvidence]=ev;else evidences.push(ev);err.textContent='';dirty=true;clearEvidence();renderEvidences();markCompleted()};
btnDraft.onclick=()=>saveDraft();
btnSend.onclick=()=>{const p=pending();if(p.length){document.getElementById('listaPendientes').innerHTML=p.map(x=>`<li>${x}</li>`).join('');showModal('modalIncompleto');return}showModal('modalEnviar')};
document.getElementById('btnRegresar').onclick=()=>{hideModal('modalIncompleto');const i=steps.findIndex(s=>!validateStep(s,false));showStep(i<0?0:i);validateStep(steps[currentStep],true)};
document.getElementById('btnBorradorModal').onclick=()=>saveDraft();
document.getElementById('btnCancelarEnvio').onclick=()=>hideModal('modalEnviar');
document.getElementById('btnConfirmarEnvio').onclick=()=>{const payload={estado:'Enviado',data:{...formData(),evidences},ultimoPaso:3,updatedAt:new Date().toLocaleString('es-PE')};localStorage.setItem(key(currentSystem),JSON.stringify(payload));localStorage.setItem(`diagti-estado-${currentSystem}`,'Enviado');addHistory(currentSystem,'Envío','El registro técnico fue enviado al Validador CTIC.','Enviado','Flujo de validación','Enviado');dirty=false;hideModal('modalEnviar');message.className='message success';message.textContent='Registro enviado al Validador CTIC. Ya no podrá editarse mientras esté en revisión.';setTimeout(()=>location.href='mis-sistemas.html',900)};
populateSystems();const params=new URLSearchParams(location.search),initial=params.get('sistema');if(initial&&systems[initial]&&(stateOf(initial)==='Nuevo'||stateOf(initial)==='Borrador')){systemSelect.value=initial;loadSystem(initial)}else{updateStatus();showStep(0);if(initial&&systems[initial]){message.className='message error';message.textContent='Este sistema ya inició el flujo de validación. Solo los sistemas Nuevos o en Borrador pueden abrirse aquí.'}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
