# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://postgres:5432/diagti_db
spring.datasource.username=postgres
spring.datasource.password=Postgres123*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info

# Puerto del servidor
server.port=8080
server.servlet.context-path=/